<a href="https://colab.research.google.com/github/bharu6522/Machine-Learning-Techniques/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Vectorization Techniques**
1. ***Bag of words***

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
doc_1 = ["Beijing, India and Pakistan should resolve their differences over the Kashmir issue peacefully through dialogue and consultation, China said on Friday on the third anniversary of the revocation of the special status of Jammu and Kashmir. In August 2019, the Indian government bifurcated Jammu and KashmirUnion territories and abrogated the provisions of Article 370 of the Constitution which accorded special status to the erstwhile state"]

In [ ]:
#create an instance of CountVectorizer.
cv = CountVectorizer()

In [ ]:
#vectorize our input and convert it into a NumPy array for viewing purposes.
X = cv.fit_transform(doc_1) 
X = X.toarray()
X

array([[1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 1, 5, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 8, 1, 1, 1, 1,
        1]])

In [ ]:
# print the vocabulary to understand why it looks like this
sorted(cv.vocabulary_.keys())

['2019',
 '370',
 'abrogated',
 'accorded',
 'and',
 'anniversary',
 'article',
 'august',
 'beijing',
 'bifurcated',
 'china',
 'constitution',
 'consultation',
 'dialogue',
 'differences',
 'erstwhile',
 'friday',
 'government',
 'in',
 'india',
 'indian',
 'issue',
 'jammu',
 'kashmir',
 'kashmirunion',
 'of',
 'on',
 'over',
 'pakistan',
 'peacefully',
 'provisions',
 'resolve',
 'revocation',
 'said',
 'should',
 'special',
 'state',
 'status',
 'territories',
 'the',
 'their',
 'third',
 'through',
 'to',
 'which']

***2. TF-IDF***
TF-IDF or Term Frequency–Inverse Document Frequency, is a numerical statistic that’s intended to reflect how important a word is to a document. Although it’s another frequency-based method


TF = frequency of word in a document / total number of that words in  documents 

DF = documents containing ord w / total number of documents 

IDF = log(total # of documents / documents containing word w ) 

TF - idf Score--> 
    TF -IDF = TF * IDF 

[https://neptune.ai/blog/vectorization-techniques-in-nlp-guide](https://)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
doc_1 = ["Beijing, India and Pakistan should resolve their differences over the Kashmir issue peacefully through dialogue and consultation, China said on Friday on the third anniversary of the revocation of the special status of Jammu and Kashmir. In August 2019, the Indian government bifurcated Jammu and KashmirUnion territories and abrogated the provisions of Article 370 of the Constitution which accorded special status to the erstwhile state"]

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
# transform the data now.
transformed = tfidf.fit_transform(doc_1)

In [ ]:
import pandas as pd
df = pd.DataFrame(transformed[0].T.todense(),
    	index=tfidf.get_feature_names(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)
#Since the transformed TFIDF feature matrix comes out as a Scipy Compressed Sparse Row matrix, 
#which can’t be viewed in its raw form, we have converted it into a Numpy array, via todense() operation 
#after taking its transform. Similarly, we get the complete vocabulary of tokenized words via get_feature_names().

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
df

                TF-IDF
the           0.611775
of            0.382360
and           0.382360
jammu         0.152944
on            0.152944
kashmir       0.152944
status        0.152944
special       0.152944
territories   0.076472
their         0.076472
state         0.076472
third         0.076472
should        0.076472
said          0.076472
revocation    0.076472
resolve       0.076472
provisions    0.076472
peacefully    0.076472
pakistan      0.076472
over          0.076472
through       0.076472
to            0.076472
kashmirunion  0.076472
2019          0.076472
370           0.076472
constitution  0.076472
abrogated     0.076472
accorded      0.076472
anniversary   0.076472
article       0.076472
august        0.076472
beijing       0.076472
bifurcated    0.076472
china         0.076472
consultation  0.076472
issue         0.076472
dialogue      0.076472
differences   0.076472
erstwhile     0.076472
friday        0.076472
government    0.076472
in            0.076472
india         0.076472
indian        0.076472
which         0.076472

In [ ]:
# similiarly for doc2 
doc_2 = ["have dropped by over 88 per cent in three years since the revocation of the erstwhile state's special status compared to the preceding three years, police said on Friday. From August 5, 2016, to August 4, 2019, the Valley witnessed 3,686 law and order incidents, as per the data shared by the police.However, for the three years from August 5, 2019 - when the Centre revoked Jammu and Kashmir's special status and bifurcated it into two Union territories "]

In [ ]:
cv1 = CountVectorizer()
Y = cv1.fit_transform(doc_2) 
Y = Y.toarray()
sorted(cv1.vocabulary_.keys())

['2016',
 '2019',
 '686',
 '88',
 'and',
 'as',
 'august',
 'bifurcated',
 'by',
 'cent',
 'centre',
 'compared',
 'data',
 'dropped',
 'erstwhile',
 'for',
 'friday',
 'from',
 'have',
 'however',
 'in',
 'incidents',
 'into',
 'it',
 'jammu',
 'kashmir',
 'law',
 'of',
 'on',
 'order',
 'over',
 'per',
 'police',
 'preceding',
 'revocation',
 'revoked',
 'said',
 'shared',
 'since',
 'special',
 'state',
 'status',
 'territories',
 'the',
 'three',
 'to',
 'two',
 'union',
 'valley',
 'when',
 'witnessed',
 'years']

In [ ]:
# tf-idf approach
tfidf_2 = TfidfVectorizer()
transformed_2 = tfidf_2.fit_transform(doc_2)
df2 = pd.DataFrame(transformed_2[0].T.todense(),index=tfidf_2.get_feature_names(), columns=["TF-IDF"])
df2 = df2.sort_values('TF-IDF', ascending=False)
df2

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

               TF-IDF
the          0.611775
years        0.229416
three        0.229416
and          0.229416
august       0.229416
2019         0.152944
per          0.152944
police       0.152944
from         0.152944
special      0.152944
status       0.152944
to           0.152944
by           0.152944
said         0.076472
witnessed    0.076472
when         0.076472
valley       0.076472
preceding    0.076472
revocation   0.076472
revoked      0.076472
shared       0.076472
two          0.076472
since        0.076472
union        0.076472
state        0.076472
order        0.076472
territories  0.076472
over         0.076472
2016         0.076472
on           0.076472
erstwhile    0.076472
686          0.076472
88           0.076472
as           0.076472
bifurcated   0.076472
cent         0.076472
centre       0.076472
compared     0.076472
data         0.076472
dropped      0.076472
for          0.076472
of           0.076472
friday       0.076472
have         0.076472
however      0.076472
in           0.076472
incidents    0.076472
into         0.076472
it           0.076472
jammu        0.076472
kashmir      0.076472
law          0.076472

In [ ]:
import numpy as np

def cosine_similarity(x, y):
    
    # Ensure length of x and y are the same
    if len(x) != len(y) :
        return None
    
    # Compute the dot product between x and y
    dot_product = np.dot(x, y)
    
    # Compute the L2 norms (magnitudes) of x and y
    magnitude_x = np.sqrt(np.sum(x**2)) 
    magnitude_y = np.sqrt(np.sum(y**2))
    
    # Compute the cosine similarity
    cosine_similarity = dot_product / (magnitude_x * magnitude_y)
    
    return cosine_similarity

In [ ]:
cos_sim_1_2 = cosine_similarity(X[0:], X[1:])

In [ ]:
cos_sim_1_2

None